version: '3.9'

services:
  axon-receivingms:
      image: axoniq/axonserver
      hostname: axon-receivingms
      ports:
        - "8026:8024"
        - "8126:8124"
        - "8226:8224"

  postgres-receivingms:
    container_name: postgres-receivingms
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - receivingms-postgres-data:/var/lib/postgresql/data
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: receivingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

volumes:
  receivingms-postgres-data:
