###add client
POST http://localhost:8383/cargopicking/clients
Content-Type: text/plain

Client 2

###get clients
GET http://localhost:8383/cargopicking/clients

###delete client
DELETE http://localhost:8383/cargopicking/clients/28806096-fd69-4ec9-bfc5-ca6b445d9a32

###add transporter
POST http://localhost:8383/cargopicking/transporters
Content-Type: text/plain

Transporter 2

###get transporters
GET http://localhost:8383/cargopicking/transporters

###delete transporter
DELETE http://localhost:8383/cargopicking/transporters/87649a07-b4f7-4dbf-8d95-7dddce8eabed

###create picking order
POST http://localhost:8383/cargopicking/create
Content-Type: application/json

{
  "clientId": "94f2195e-6fc8-4039-a366-4465fae7f738",
  "clientName": "Client 1",
  "transporterId": "52a48f32-c413-4a6c-8892-efc8cc5c7ab7",
  "transporterName": "Transporter 1",
  "preparationDeadline": "2024-06-10T10:30:00"
}

###add detail to picking order
POST http://localhost:8383/cargopicking/add_detail
Content-Type: application/json

{
  "pickingOrderId": "cf5e86a6-62c7-4904-99f0-5cc48ec8570c",
  "skuBarcode": "1234554235432",
  "skuName": "Product Name 3",
  "skuDecription": "Product 3 Description",
  "qty": 20,
  "packType": "CARTON",
  "packDescription": "Pack Description"
}

###remove detail from picking order
POST http://localhost:8383/cargopicking/remove_detail
Content-Type: application/json

{
  "pickingOrderId": "cf5e86a6-62c7-4904-99f0-5cc48ec8570c",
  "detailId": "e8f6b27e-0eeb-4376-946a-4058d4511e20"
}

###pick cargo
POST http://localhost:8383/cargopicking/pick_cargo
Content-Type: application/json

{
  "pickingOrderId": "fe07802f-5d5a-4e52-b221-33784b839d34",
  "detailId": "62dc3584-9126-43b0-8b82-24a831bbcfb8",
  "cargoId": "a26ac53d-11ec-4d0e-aa0a-1c5cb4203f7d",
  "skuPickingStatus": "PICKED"
}

###delete picking order
DELETE http://localhost:8383/cargopicking
Content-Type: application/json

{
  "id": "cf5e86a6-62c7-4904-99f0-5cc48ec8570c"
}

###get picking orders
GET http://localhost:8383/cargopicking

###

GET http://localhost:8383/cargopicking/912d8de3-25e9-4915-9661-ec83615d73e3/events
Content-Type: application/json
