###add client
POST http://localhost:8383/cargopicking/clients
Content-Type: text/plain

EcoTech Solutions

###get clients
GET http://localhost:8383/cargopicking/clients

###delete client
DELETE http://localhost:8383/cargopicking/clients/28806096-fd69-4ec9-bfc5-ca6b445d9a32

###add transporter
POST http://localhost:8383/cargopicking/transporters
Content-Type: text/plain

RapidMove Logistics

###get transporters
GET http://localhost:8383/cargopicking/transporters

###delete transporter
DELETE http://localhost:8383/cargopicking/transporters/87649a07-b4f7-4dbf-8d95-7dddce8eabed

###create picking order
POST http://localhost:8383/cargopicking/create
Content-Type: application/json

{
  "clientId": "efe111a9-e47e-430f-82c4-c36e30efb456",
  "clientName": "EcoTech Solutions",
  "transporterId": "203bf51a-21bb-4955-a381-d674f363de56",
  "transporterName": "RapidMove Logistics",
  "preparationDeadline": "2024-06-08T08:00:00"
}

###add detail to picking order
POST http://localhost:8383/cargopicking/add_detail
Content-Type: application/json

{
  "pickingOrderId": "4f83b727-391a-4ab5-a65a-3977b4d82f35",
  "skuBarcode": "9876543210987",
  "skuName": "Tech Glow",
  "skuDecription": "State-of-the-art smart LED light bulb with customizable color temperature and brightness settings.",
  "qty": 25,
  "packType": "CARTON",
  "packDescription": "Carton-x1-Unit-x5"
}

###remove detail from picking order
POST http://localhost:8383/cargopicking/remove_detail
Content-Type: application/json

{
  "pickingOrderId": "cf5e86a6-62c7-4904-99f0-5cc48ec8570c",
  "detailId": "e8f6b27e-0eeb-4376-946a-4058d4511e20"
}

###pick cargo
POST http://localhost:8383/cargopicking/pick_cargo
Content-Type: application/json

{
  "pickingOrderId": "4f83b727-391a-4ab5-a65a-3977b4d82f35",
  "detailId": "cc38869d-9977-4458-9a58-e0746395dfbc",
  "cargoId": "31518631-e814-4f92-b179-d97b0f4eb717",
  "skuPickingStatus": "PARTIALLY_DONE"
}

###change status of PO
POST http://localhost:8383/cargopicking/change_status
Content-Type: application/json

{
  "id": "4f83b727-391a-4ab5-a65a-3977b4d82f35",
  "status": "PARTIALLY_DONE"
}

###change status of PO
POST http://localhost:8383/cargopicking/change_detail_status
Content-Type: application/json

{
  "id": "4f83b727-391a-4ab5-a65a-3977b4d82f35",
  "detailId": "dd31a1cd-a08a-4a6b-9d57-5f7457ccd235",
  "status": "CANCELED"
}

###delete picking order
DELETE http://localhost:8383/cargopicking
Content-Type: application/json

{
  "id": "cf5e86a6-62c7-4904-99f0-5cc48ec8570c"
}

###get picking orders
GET http://localhost:8383/cargopicking

###

GET http://localhost:8383/cargopicking/912d8de3-25e9-4915-9661-ec83615d73e3/events
Content-Type: application/json
