version: '3.9'

services:
  axon-storingms:
    image: axoniq/axonserver
    hostname: axon-storingms
    ports:
      - "8024:8024"
      - "8124:8124"
      - "8224:8224"

  postgres-storingms:
    container_name: postgres-storingms
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - storingms-postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: storingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

volumes:
  storingms-postgres-data:
