POST http://localhost:8282/cargostoring/create
Content-Type: application/json

{
    "skuBarcode": "12345",
    "skuName": "sku",
    "skuDescription": "test sku",
    "packType": "CARTON",
    "packDescription": "test carton",
    "qtyOfSku": 12 
}

###

POST http://localhost:8282/cargostoring/move
Content-Type: application/json

{
    "id": "4695dfc1-19f1-48d8-93ed-ca73ec0d40d1",
    "zone": "A1",
    "cell": "C5"
}

###

POST http://localhost:8282/cargostoring/update
Content-Type: application/json

{
    "id": "4695dfc1-19f1-48d8-93ed-ca73ec0d40d1",
    "qty": 90
}

###

POST http://localhost:8282/cargostoring/changestatus
Content-Type: application/json

{
    "id": "4695dfc1-19f1-48d8-93ed-ca73ec0d40d1",
    "status": "BLOCKED"
}

###

DELETE http://localhost:8282/cargostoring
Content-Type: application/json

{
    "id": "4695dfc1-19f1-48d8-93ed-ca73ec0d40d1"
}

###

GET http://localhost:8282/cargostoring
Content-Type: application/json
