POST http://localhost:8080/cargostoring/create
Content-Type: application/json

{
    "skuBarcode": "12345",
    "skuName": "sku",
    "skuDescription": "test sku",
    "packType": "CARTON",
    "packDescription": "test carton",
    "qtyOfSku": 12 
}

###

POST http://localhost:8080/cargostoring/update
Content-Type: application/json

{
    "id": "6947b88d-6b91-441e-a59c-45781666dbba",
    "qty": 90
}

###

DELETE http://localhost:8080/cargostoring
Content-Type: application/json

{
    "id": "a1f3bbaa-750b-4cd7-aa9d-efdbc89ba1d5"
}

###
