POST http://localhost:8080/api/v1/cargo/create
Content-Type: application/json

{
    "skuBarcode": "12345",
    "skuName": "sku",
    "skuDescription": "test sku",
    "packType": "CARTON",
    "packDescription": "test carton",
    "qtyOfSku": 5 
}

###

POST http://localhost:8080/api/v1/cargo/update
Content-Type: application/json

{
    "id": "a41fa65a-13e9-40a0-b176-fa01df6e29d5",
    "qty": 8
}

###
