### add supplier
POST http://localhost:8181/cargoreceiving/suppliers
Content-Type: text/plain

PrimeSupply

### get suppliers
GET http://localhost:8181/cargoreceiving/suppliers

### delete supplier
DELETE http://localhost:8181/cargoreceiving/suppliers/1bfd1897-21f5-4e81-9e38-be63ab45a769

### add transporter
POST http://localhost:8181/cargoreceiving/transporters
Content-Type: text/plain

SwiftTransport

### get transporters
GET http://localhost:8181/cargoreceiving/transporters

### delete transporter
DELETE http://localhost:8181/cargoreceiving/suppliers/1bfd1897-21f5-4e81-9e38-be63ab45a769

### create receiving order
POST http://localhost:8181/cargoreceiving/create
Content-Type: application/json

{
  "supplierId": "3da6763d-dbda-4614-bfa1-adb0d0ddb2b6",
  "supplierName": "PrimeSupply",
  "transporterId": "82355772-bc71-4d7f-864f-95266a4dbf63",
  "transporterName": "SwiftTransport",
  "date": "2024-06-08T02:30:00"
}

###add detail to receiving order
POST http://localhost:8181/cargoreceiving/add_detail
Content-Type: application/json

{
  "receivingOrderId": "fdfd5087-07f5-4a4e-92df-2b13c08836fa",
  "skuBarcode": "8718692615091",
  "skuName": "Smart Fitness Tracker",
  "skuDecription": "Smart fitness tracker designed to track activity, heart rate, and sleep for maintaining a healthy lifestyle.",
  "qty": 295,
  "packType": "CARTON",
  "packDescription": "Carton-x1-Unit-x10"
}

###remove detail from receiving order
POST http://localhost:8181/cargoreceiving/remove_detail
Content-Type: application/json

{
  "receivingOrderId": "4af32797-9dc4-4717-b39b-9b5545c7837c",
  "detailId": "64fa52c5-4901-4e8d-b615-cf5ddf3fe11c"
}

###receive cargo
POST http://localhost:8181/cargoreceiving/receive_cargo
Content-Type: application/json

{
  "receivingOrderId": "fdfd5087-07f5-4a4e-92df-2b13c08836fa",
  "detailId": "d0ae1177-06ce-421a-af8f-a1d2694ca6a3",
  "cargoId": "31518631-e814-4f92-b179-d97b0f4eb717",
  "skuReceivingStatus": "RECEIVED_PARTIALLY"
}

###change status
POST http://localhost:8181/cargoreceiving/change_status
Content-Type: application/json

{
  "id": "fdfd5087-07f5-4a4e-92df-2b13c08836fa",
  "status": "PARTIALLY_DONE"
}

###delete receiving order
DELETE http://localhost:8181/cargoreceiving
Content-Type: application/json

{
  "id": "4af32797-9dc4-4717-b39b-9b5545c7837c"
}

### get receiving orders
GET http://localhost:8181/cargoreceiving

###

GET http://localhost:8181/cargoreceiving/912d8de3-25e9-4915-9661-ec83615d73e3/events
Content-Type: application/json