### add supplier
POST http://localhost:8181/cargoreceiving/suppliers
Content-Type: text/plain

Supplier 1

### get suppliers
GET http://localhost:8181/cargoreceiving/suppliers

### delete supplier
DELETE http://localhost:8181/cargoreceiving/suppliers/1bfd1897-21f5-4e81-9e38-be63ab45a769

### add transporter
POST http://localhost:8181/cargoreceiving/transporters
Content-Type: text/plain

Transporter 2

### get transporters
GET http://localhost:8181/cargoreceiving/transporters

### delete transporter
DELETE http://localhost:8181/cargoreceiving/suppliers/1bfd1897-21f5-4e81-9e38-be63ab45a769

### create receiving order
POST http://localhost:8181/cargoreceiving/create
Content-Type: application/json

{
  "supplierId": "097275e9-1698-4723-b753-1b0c5cd3a2ad",
  "supplierName": "Supplier 1",
  "transporterId": "d4f1bd50-bd02-4308-9829-9d4ebc5251f3",
  "transporterName": "Transporter 2",
  "date": "2024-07-01T10:30:00"
}

###add detail to receiving order
POST http://localhost:8181/cargoreceiving/add_detail
Content-Type: application/json

{
  "receivingOrderId": "4af32797-9dc4-4717-b39b-9b5545c7837c",
  "skuBarcode": "12345678",
  "skuName": "Product Name 3",
  "skuDecription": "Product 3 Description",
  "qty": 10,
  "packType": "PALLET",
  "packDescription": "Pack Description for Pallet 2"
}

###remove detail from receiving order
POST http://localhost:8181/cargoreceiving/remove_detail
Content-Type: application/json

{
  "receivingOrderId": "4af32797-9dc4-4717-b39b-9b5545c7837c",
  "detailId": "64fa52c5-4901-4e8d-b615-cf5ddf3fe11c"
}

###receive cargo
POST http://localhost:8181/cargoreceiving/receive_cargo
Content-Type: application/json

{
  "receivingOrderId": "4af32797-9dc4-4717-b39b-9b5545c7837c",
  "detailId": "80463c4f-ae8f-43dc-a3fb-1cb228f8d2e9",
  "cargoId": "0b138ff3-e1ca-4b22-b69e-8e974c2aa6e6",
  "skuReceivingStatus": "RECEIVED_PARTIALLY"
}

###delete receiving order
DELETE http://localhost:8181/cargoreceiving
Content-Type: application/json

{
  "id": "4af32797-9dc4-4717-b39b-9b5545c7837c"
}

### get receiving orders
GET http://localhost:8181/cargoreceiving

###

GET http://localhost:8181/cargoreceiving/912d8de3-25e9-4915-9661-ec83615d73e3/events
Content-Type: application/json